PREFIX : <http://example.org/ca-map/>

SELECT ?company ?member
WHERE {
  VALUES ?company {
    :Vinamilk
    :Hanoi_Metro
    :Đấu_giá_Lạc_Việt
  }
  ?company :có_thành_viên ?member .
}
ORDER BY ?company ?member
