PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/luat-doanh-nghiep/>

SELECT ?member ?inferredClass
WHERE {
  VALUES ?inferredClass {
    :Thành_viên
  }
  ?member rdf:type ?inferredClass .
}
ORDER BY ?member
